#image_encoder = "ViTModel.from_pretrained('google/vit-base-patch16-224')"
#image_feature_extractor = "ViTFeatureExtractor.from_pretrained('google/vit-base-patch16-224')"
#image_processor = "ViTImageProcessor.from_pretrained('google/vit-base-patch16-224')"

#image_encoder = "ViTModel.from_pretrained('facebook/dino-vitb16')"
#image_feature_extractor = "ViTFeatureExtractor.from_pretrained('facebook/dino-vitb16')"
#image_processor = "ViTImageProcessor.from_pretrained('facebook/dino-vitb16')"

#image_encoder = "AutoModel.from_pretrained('facebook/dinov2-small')"
#image_feature_extractor = "None"
#image_processor = "AutoImageProcessor.from_pretrained('facebook/dinov2-small')"


image_encoder = "ViTModel.from_pretrained('facebook/deit-base-patch16-224')"
image_feature_extractor = "None"
image_processor = "DeiTImageProcessor.from_pretrained('facebook/deit-base-patch16-224')"
